name: Pipeline
on: [push]
jobs:
  teste:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 15
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: npm test
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          reviewers: duiliofelix
          branch: dev
          delete-branch: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: fzm-teste-ecr
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t fzm-teste-ecr .
          docker tag fzm-teste-ecr:latest public.ecr.aws/y7l4l2h9/fzm-teste-ecr:latest
          docker push public.ecr.aws/y7l4l2h9/fzm-teste-ecr:latest